gui:
  splitDiff: "auto" # one of 'auto' | 'always'
  showBottomLine: false
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  showFileIcons: false
  border: "normal" #"rounded"
promptToReturnFromSubprocess: true
git:
  log:
    showGraph: always
    showWholeGraph: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  edit: "nvim {{filename}}"
  # --remote-send "<cmd>lua require('core.scripts.lazygit-open-file')('{{filename}}', '{{line}}')<CR>"
  # editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
  # editCommandTemplate: nvim --server /tmp/nvim-server.pipe --remote-send "<cmd>lua require('scripts.lazygit')('{{filename}}', '{{line}}')<CR>"

customCommands:
  - key: "a"
    context: "localBranches"
    command: "git pull; git pull --tags"
  - key: "A"
    context: "localBranches"
    command: "git push; git push --tags"
