-- Generated by nwg-displays on 2026-07-01 at 22:00:18. Do not edit manually.

hl.monitor({
    output = "desc:Samsung Display Corp. ATNA60HU01-0",
    mode = "2560x1600@60.0",
    position = "2887x1662",
    scale = 1.6
})
hl.monitor({
    output = "desc:BNQ BenQ EW3270U Y1K01098019",
    mode = "3840x2160@60.0",
    position = "967x1582",
    scale = 2.0
})
