-- Generated by nwg-displays on 2026-06-09 at 19:12:50. Do not edit manually.

hl.monitor({
    output = "desc:Samsung Display Corp. ATNA60HU01-0",
    mode = "2560x1600@240.0",
    position = "550x1020",
    scale = 1.6
})
hl.monitor({
    output = "desc:DHI LM24-A200Y 0x00000001",
    mode = "1920x1080@60.0",
    position = "2150x940",
    scale = 1.0
})
