
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2
#


env = mo_helpers, $scrPath
# Monitors
# monitor=eDP-1,1920x1080@120,0x0,1.2 # laptop
# monitor=HDMI-A-1, preferred, 1600x0, 1.6
# monitor= desc:LG Electronics LG ULTRAGEAR 308NTKF2S389, preferred, 0x-1152, 1.25
# monitor=DP-1, preferred, 1600x0, 1
# monitor=DP-2, preferred, 1600x0, 1.6
# monitor= desc:DHI, preferred,1600x0,1
# monitor=desc:DHI LM24-A200Y 0x00000001,1920x1080@100.0,1912x518,1.0
# monitor= desc:RGT, preferred,1600x0,1 # home screen
# monitor=desc:Samsung Display Corp. ATNA60HU01-0,2560x1600@240.0,2887x1436,1.6
# monitor=desc:BNQ BenQ EW3270U Y1K01098019,3840x2160@60.0,0x812,1.33
monitor=desc:DHI LM24-A200Y 0x00000001,1920x1080@100.0,2150x940,1.0

# Workspaces
workspace = 1,monitor:eDP-1
workspace = 2,monitor:eDP-1
# workspace = r[1-4],monitor:eDP-1, default:true, gapsout:0
# workspace = 1, monitor:HDMI-A-1, default:true
# workspace = 2, monitor:HDMI-A-1
# workspace = 3, monitor:HDMI-A-1


# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

# See https://wiki.hyprland.org/Configuring/Keywords/
exec-once = solaar -w hide #logitec mouse
# exec = gsettings set org.gnome.desktop.interface gtk-theme 'Decay-Green'
exec-once = kwalletd6 &
# exec-once = waybar &
exec-once = syncthing --no-browser &

# Animation CPU usage fix
animations {
    enabled = yes
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, liner
    # animation = borderangle, 1, 30, liner, loop
    animation = fade, 1, 10, default
    animation = workspaces, 1, 5, wind
}

input {
    kb_layout = fr,us
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
    }

    sensitivity = 0.5
    force_no_accel = 0
    numlock_by_default = true
}


# touchpad sensitivity, works only if force_no_accel = 0
device {
  name = gxtp5100:00-27c6:01e0-touchpad
  sensitivity = 0.5
}


cursor {
  no_hardware_cursors = false
}

decoration {
    rounding = 0
}
# window effects

